### ISSUE TITLE
Missing Unit Tests

### ISSUE THREAD

**Issue by valendesigns** [PacktPublishing/Learning-Vue.js-2#1]
The unit tests for `createShoppingList` & `deleteShoppingList` from `actions.js` in chapter 7 are missing from this repository. It's not exactly clear how to test these methods. Please add the tests or explain how to go about testing them here. As well, please go into further detail about the syntax in the method.

```js
createShoppingList: (store, shoppinglist) => {
  return api.addNewShoppingList(shoppinglist).then(() => {
    store.dispatch('populateShoppingLists')
  }, () => {
    store.commit(types.ADD_SHOPPING_LIST, shoppinglist)
  })
}
```

I don't understand why are there two objects and one being call like `() => {...}`

**Comment by ghost** [comment]
I agreewth you about missing unit tests and details ..

hereafter are my unit tests if it can help

`  describe('createShoppingList', () => {
    it('should return successful POST response', () => {
      let newList = { title: 'new list', id: '3' }
      actions.createShoppingList(store, newList).then((resp) => {
        expect(resp.body).to.eql(successPost)
      })
    })
  })

  describe('deleteShoppingList', () => {
    it('should return successful DELETE response', () => {
      actions.deleteShoppingList(store, '1').then((resp) => {
        expect(resp.body).to.eql(successDelete)
      })
    })
  })`

regarding the details , api.addNewShoppingList() is a Promise.. better writing would be 👍 
`return api.addNewShoppingList(shoppinglist)
.then(
() => { store.dispatch('populateShoppingLists')}, 
() => { store.commit(types.ADD_SHOPPING_LIST, shoppinglist) }
)
`
store.dispatch() ans store.commit are executed when the api.addNewShoppingList() promise is resolved, and it's response is returned ( { post: true }  object is returned...)

hope it helps

**Comment by ghost** [comment]
BTW there is a BUG in this code as it's written 👍  the .then block means 

`.then(resolved, rejected)`

so as it is written, store.commit() is executed when resolved  and   store.dispatch() when it is rejected  , which is BAD, as both  ( commit and dispatch  SHOULD be executed when the Promise is resolved .. so in my opinion it should be written 👍 

`
      createShoppingList: (store, shoppinglist) => {
         return api.addNewShoppingList(shoppinglist).then(
           () => {
             store.commit(types.ADD_SHOPPING_LIST, shoppinglist)
             store.dispatch('populateShoppingLists')
           }
         )
  },
`

**Comment by sonam-packt** [comment]
Please reopen if the issue still persist
