### ISSUE TITLE
Chapter 4, title changing in shopping-list2

### ISSUE THREAD

**Issue by mchlcrtz** [PacktPublishing/Learning-Vue.js-2#10]
In the text, the steps say to do the following:
1. Bind the model title using the v-model directive to change-title-component in the template of the ShoppingListComponent.
2. Export value in the props attribute of the ChangeTitleComponent.
3. Create an onInput method inside the ChangeTitleComponent that will emit
the native input method with the value of the event target.
4. Bind value to input inside the ChangeTitleComponent component's template
and the v-on directive with the onInput modifier.

In step 4, the functionality works fine without binding the value to input and declaring any props:
<template>
<...>
<input @input = "onInput"/> 
<...>
</template>

So why do we need to bind value to input inside the ChangeTitleComponent component's template and declare props if we are not receiving and value props inside the component in ShoppingListComponent? 
// ShoppingListComponent
<<change-title-component v-model="title"></change-title-component>

// ChangeTitleComponent
<input :value = "value" @input ="onInput"/>

**Comment by gaurav-packt** [comment]
Please reopen the issue if it still exists.
