### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BigSully** [PacktPublishing/Learning-Vue.js-2#3]
https://github.com/PacktPublishing/Learning-Vuejs-2/blob/master/chapter6/shopping-list2/package.json

[error] "server": "node_modules/json-server/bin/index.js --watch server/db.json",
[fix]  "server": "node node_modules/json-server/bin/index.js --watch server/db.json",

**Comment by sohamapackt** [comment]
Hi,

i am closing the issue. 
In case the issue still persists, feel free to reopen it.

Thanks
