### ISSUE TITLE
Inconsistency in code sample for Chapter5/Pomodoro

### ISSUE THREAD

**Issue by wycoconut** [PacktPublishing/Learning-Vue.js-2#4]
Just a note to anyone following the book, Chapter 5.

According to this file :

Learning-Vuejs-2/chapter5/pomodoro/package.json

This sample is using Vue JS v1, and already has the components and vuex stuff (I assume specific for that version). There are also some differences in how the getters are defined for CountdownComponent.vue based in the book.

Code sample 
```javascript
  import { getMinutes, getSeconds } from '../vuex/getters'

  export default {
    vuex: {
      getters: {
        min: getMinutes,
        sec: getSeconds
      }
    }
  }
```

Book 
```javascript
import { mapGetters } from 'vuex'

export default {
  computed: mapGetters({
    min: 'getMinutes',
    sec: 'getSeconds'
  })
}
```

As a result, students cannot follow through (from scratch) with the chapter's exercise if taking the source code from Learning-Vuejs-2/chapter5/pomodoro.

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
